# Generated by Django 2.0.1 on 2018-05-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitlab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('reqid', models.CharField(max_length=200, unique=True)),
                ('reply_json', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GraphUiRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('syncset', models.TextField(blank=True)),
            ],
        ),
    ]
