# Generated by Django 2.0.1 on 2018-06-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitlab', '0003_graphsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphsession',
            name='gs_id',
        ),
        migrations.AddField(
            model_name='graphdef',
            name='gs_id',
            field=models.CharField(default='hest', max_length=200),
            preserve_default=False,
        ),
    ]
