# Generated by Django 2.0.1 on 2018-06-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitlab', '0004_auto_20180628_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphdef',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
