# Generated by Django 2.0.1 on 2018-06-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitlab', '0005_auto_20180628_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphuirequest',
            name='gs_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
