# Generated by Django 2.0.1 on 2018-06-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitlab', '0008_remove_graphuirequest_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphuirequest',
            name='username',
            field=models.CharField(default='admin', max_length=200),
            preserve_default=False,
        ),
    ]
