# Generated by Django 2.0.1 on 2018-07-05 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitlab', '0010_auto_20180704_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphuirequest',
            name='completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='completed'),
        ),
        migrations.AddField(
            model_name='graphuirequest',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='graphuirequest',
            name='started',
            field=models.DateTimeField(blank=True, null=True, verbose_name='started'),
        ),
    ]
