# Generated by Django 2.0.1 on 2018-07-05 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitlab', '0011_auto_20180705_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphuirequest',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='graphuirequest',
            name='created',
        ),
        migrations.RemoveField(
            model_name='graphuirequest',
            name='started',
        ),
    ]
