# Generated by Django 2.0.1 on 2018-07-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitlab', '0014_auto_20180706_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphsession',
            name='quicksave_pickle',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='graphsession',
            name='stashed_pickle',
            field=models.TextField(blank=True),
        ),
    ]
