# Generated by Django 2.0.1 on 2018-07-10 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitlab', '0015_auto_20180706_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphsession',
            name='stashed_undostack',
        ),
        migrations.AddField(
            model_name='graphreply',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='graphuirequest',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
    ]
