# Generated by Django 2.0.1 on 2018-07-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitlab', '0016_auto_20180710_1125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GraphDef',
        ),
        migrations.AddField(
            model_name='graphreply',
            name='reply_error',
            field=models.TextField(blank=True),
        ),
    ]
