# Generated by Django 2.0.1 on 2018-07-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitlab', '0017_auto_20180711_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphreply',
            name='reply_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
