# Generated by Django 2.0.1 on 2018-07-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitlab', '0018_auto_20180711_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphsession',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='graphsession',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
