# Generated by Django 2.0.1 on 2018-07-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitlab', '0019_auto_20180712_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphsession',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='graphsession',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
