# Generated by Django 2.0.1 on 2018-07-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitlab', '0021_graphsession_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gs_id', models.CharField(max_length=200)),
            ],
        ),
    ]
