# Generated by Django 2.0.1 on 2018-07-23 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitlab', '0022_tabid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabid',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
    ]
