# Generated by Django 2.0.1 on 2018-07-23 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitlab', '0023_tabid_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabid',
            name='touched',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='touched'),
        ),
    ]
