# Generated by Django 2.0.1 on 2018-07-26 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitlab', '0024_tabid_touched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabid',
            name='touched',
        ),
    ]
