# Generated by Django 2.0.1 on 2018-08-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitlab', '0025_remove_tabid_touched'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphsession',
            old_name='quicksave_graphdef',
            new_name='graphdef',
        ),
        migrations.RemoveField(
            model_name='graphsession',
            name='stashed_graphdef',
        ),
    ]
