# Generated by Django 2.0.1 on 2018-08-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitlab', '0026_auto_20180813_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphsession',
            name='listidx',
            field=models.IntegerField(default=0),
        ),
    ]
