# Generated by Django 2.0.1 on 2018-08-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitlab', '0027_graphsession_listidx'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphsession',
            name='excomment',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
