# Generated by Django 2.0.1 on 2018-08-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitlab', '0028_graphsession_excomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphsession',
            name='loglines',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='graphsession',
            name='quicksave_matfile',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='graphsession',
            name='stashed_matfile',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
